/// Generic dimensions
const MARGIN_ZERO = 0.0;
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;

const DIVIDER_THICKNESS = 1.0;

const GAME_DETAIL_PAGE_DESCRIPTION_LINE = 2;
